version: "3"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
  client:
      image: node
      environment:
          chatgpt_api_key: ""
          mongo_host: ""
      ports:
          - 3000:80
      volumes:
          - ./frontend:/usr/src
      command: bash -c "cd /usr/src && npm install && npm dev"